name: todo_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # It's good practice to use a range

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  # Moved flutter_launcher_icons to dev_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # This is a development tool, so it belongs here
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  # Make sure your assets folder is declared if you haven't already
  assets:
    - assets/

# The flutter_launcher_icons config must be indented at the same level as uses-material-design
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"