// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLOiMV21SJIUYLm0nA_qGqHcjDg4feCew',
    appId: '1:383277827031:web:413bf9b613197851a78192',
    messagingSenderId: '383277827031',
    projectId: 'dev-challenge-app',
    authDomain: 'dev-challenge-app.firebaseapp.com',
    storageBucket: 'dev-challenge-app.firebasestorage.app',
    measurementId: 'G-VXT0BNJEE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl39uUASOoYBMHs-7UBTmN78ABrsOSrYQ',
    appId: '1:383277827031:android:41743aa131e1ed7ea78192',
    messagingSenderId: '383277827031',
    projectId: 'dev-challenge-app',
    storageBucket: 'dev-challenge-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_h3SrFfzhR0n3HJ2wGn1ge7puzttFnDc',
    appId: '1:383277827031:ios:d175315495c8c335a78192',
    messagingSenderId: '383277827031',
    projectId: 'dev-challenge-app',
    storageBucket: 'dev-challenge-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_h3SrFfzhR0n3HJ2wGn1ge7puzttFnDc',
    appId: '1:383277827031:ios:d175315495c8c335a78192',
    messagingSenderId: '383277827031',
    projectId: 'dev-challenge-app',
    storageBucket: 'dev-challenge-app.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLOiMV21SJIUYLm0nA_qGqHcjDg4feCew',
    appId: '1:383277827031:web:ed07e5c54dbf1508a78192',
    messagingSenderId: '383277827031',
    projectId: 'dev-challenge-app',
    authDomain: 'dev-challenge-app.firebaseapp.com',
    storageBucket: 'dev-challenge-app.firebasestorage.app',
    measurementId: 'G-LFZG6EPPLB',
  );
}
